Command failed: /Applications/Onlook.app/Contents/Resources/bun/bun-aarch64 run build $ next build
Failed to compile.

./app/currently-reading/page.tsx
130:49  Error: `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.  react/no-unescaped-entities
130:64  Error: `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.  react/no-unescaped-entities

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error: script "build" exited with code 1